spring.application.name=fseabackend


spring.datasource.url=jdbc:postgresql://localhost:5432/fsea_db
spring.datasource.username=fsea_user
spring.datasource.password=secret123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret= 01300120319891201031023003120301
jwt.issuer: finconecta
jwt.expiration: 36000002

